.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "FPC" "1" "April 2023" ""
.SH "NAME"
\fBfpc\fR \- Free Python Cache
.SH "DESCRIPTION"
when using a lot of python commands (in gterminal), it can get very bloated with __pycache__ directories\. therefore this program searches your system and removes them, keeping it clean and pristine for the future\.
.P
this program is free\. please use it if you want to clean your system\. this comes with gterminal\.
