.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GFSC" "1" "April 2023" ""
.SH "NAME"
\fBgfsc\fR \- The Standard Filesystem Checker
.SH "DESCRIPTION"
This software is the standard file structure checker\. It supports FS64, FSU86, U86, U86R, and SW12 filesystems\.
.SH "SYNOPSIS"
\fBgfsc [no arguments]\fR
